create table if not exists public.napoli_orders (
  id text primary key check (id ~ '^nap_[a-f0-9]{32}$'),
  idempotency_key text not null unique check (char_length(idempotency_key) between 13 and 220),
  status text not null check (status in ('confirmed','preparing','baking','ready_for_handoff','out_for_delivery','ready_for_pickup','delivered','picked_up','cancelled')),
  fulfillment_mode text not null check (fulfillment_mode in ('delivery','pickup')),
  total_minor integer not null check (total_minor >= 0),
  order_payload jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.napoli_order_events (
  id bigint generated by default as identity primary key,
  order_id text not null references public.napoli_orders(id) on delete cascade,
  status text not null check (status in ('confirmed','preparing','baking','ready_for_handoff','out_for_delivery','ready_for_pickup','delivered','picked_up','cancelled')),
  created_at timestamptz not null default now()
);

create index if not exists napoli_order_events_order_created_idx
  on public.napoli_order_events (order_id, created_at);

alter table public.napoli_orders enable row level security;
alter table public.napoli_order_events enable row level security;

revoke all on public.napoli_orders from anon, authenticated;
revoke all on public.napoli_order_events from anon, authenticated;
grant select, insert, update on public.napoli_orders to service_role;
grant select, insert on public.napoli_order_events to service_role;
grant usage, select on sequence public.napoli_order_events_id_seq to service_role;

comment on table public.napoli_orders is 'Napoli guest orders; accessible only through the server-side API.';
comment on column public.napoli_orders.order_payload is 'Full active order snapshot; contains guest PII and must not be exposed to anon/authenticated roles.';
